package com.mycompany.hibernatemodel.entities;
// Generated Apr 22, 2017 12:48:04 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * ContactsInfo generated by hbm2java
 */

public class ContactsInfo  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String mobileNumber;
     private String name;
     private Set<User> users = new HashSet<User>(0);

    public ContactsInfo() {
    }

	
    public ContactsInfo(String email, String mobileNumber, String name) {
        this.email = email;
        this.mobileNumber = mobileNumber;
        this.name = name;
    }
    public ContactsInfo(String email, String mobileNumber, String name, Set<User> users) {
       this.email = email;
       this.mobileNumber = mobileNumber;
       this.name = name;
       this.users = users;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMobileNumber() {
        return mobileNumber;
    }

    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<User> getUsers() {
        return users;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }
   
    


}


